"""Add winner and timestamp to debates

Revision ID: a63c2c2d4b2d
Revises: cf8215e87da5
Create Date: 2025-07-25 10:41:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63c2c2d4b2d'
down_revision: Union[str, None] = 'cf8215e87da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('winner', sa.String(), nullable=True))
    op.add_column('debates', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'timestamp')
    op.drop_column('debates', 'winner')
    # ### end Alembic commands ###
