"""revise 2

Revision ID: bc4d17171708
Revises: c7bb4adc4f67
Create Date: 2025-07-22 14:23:49.662809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc4d17171708'
down_revision: Union[str, Sequence[str], None] = 'c7bb4adc4f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('debates', sa.Column('stance', sa.String(), nullable=False))
    op.alter_column('debates', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_debates_topic'), table_name='debates')
    op.drop_constraint(op.f('debates_client_1_id_fkey'), 'debates', type_='foreignkey')
    op.drop_constraint(op.f('debates_client_2_id_fkey'), 'debates', type_='foreignkey')
    op.create_foreign_key(None, 'debates', 'users', ['user_id'], ['id'])
    op.drop_column('debates', 'client_2_id')
    op.drop_column('debates', 'client_1_id')
    op.drop_column('debates', 'created_at')
    op.alter_column('messages', 'debate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'debate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('debates', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('debates', sa.Column('client_1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('debates', sa.Column('client_2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'debates', type_='foreignkey')
    op.create_foreign_key(op.f('debates_client_2_id_fkey'), 'debates', 'users', ['client_2_id'], ['id'])
    op.create_foreign_key(op.f('debates_client_1_id_fkey'), 'debates', 'users', ['client_1_id'], ['id'])
    op.create_index(op.f('ix_debates_topic'), 'debates', ['topic'], unique=False)
    op.alter_column('debates', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('debates', 'stance')
    op.drop_column('debates', 'user_id')
    # ### end Alembic commands ###
