"""revise 4

Revision ID: cf8215e87da5
Revises: 8d5b7cd962a2
Create Date: 2025-07-23 16:42:46.218537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8215e87da5'
down_revision: Union[str, Sequence[str], None] = '8d5b7cd962a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('elo', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('mind_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mind_tokens')
    op.drop_column('users', 'elo')
    # ### end Alembic commands ###
